jwt:
  secret: your#jwt#secret#key#here#and#do#not#upload#website#even#github
  access-token-validity-in-seconds: 120 # 2 * 1m(60s) = 2m
  refresh-token-validity-in-seconds: 1296000 # 15 * 1day(24 * 1h(60 * 1m(60s))) = 15days
  cookie-domain: "localhost:8080"

spring:
  datasource:
    url: jdbc:mysql://localhost/[YOUR_DATABSE_NAME]?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

  redis:
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        min-wait: -1

  devtools:
    livereload:
      enabled: true

logging:
  level:
    # root: INFO
    org:
      hibernate:
        SQL: debug
    # type: trace

mail:
  host: [SMPT_HOST]
  port: [PORT]
  username: [USERNAME]
  password: [PASSWORD]
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: [DOMAIN]
          protocols: TLSv1.2